### ISSUE TITLE
Roadmap, suggestions

### ISSUE THREAD

**Issue by papyr** [mcintyre321/FormFactory#14]
This has become so vital to my development, not sure why others are not using it. 

*  Can we please get a small roadmap going, at least one or two features so people can contribute or influence it. I want to hear more on where this is going.
*  For other devs - It takes some time to get fluent in getting used to *FormFactory*, but after then its worth the investment. 

Its like Zencoding for C#, it gives you the same boost!

**Comment by mcintyre321** [comment]
Thanks, it's awesome that you are using it successfully. 

I develop it on an as-needed basic. I use it in a variety of projects from normal mvc sites to dynamically building ui over hypermedia json api's. It's great if you are happy with ASP MVC, but server-side rendering is getting less trendy

There are some directions I've considered taking it in the future, but I'm not sure if they require a v2, or to be in a different project. Here are some of them:

Small things
-------

 - Fix the stackoverflow bug that occurs when the .object template attempts to render a recursive object
 - Use Selectize.js to create a multi option picker rather than the pants built in multi-select
 - Write more compelling documentation and examples
 

HUGE: Decouple from ASP.NET and allow clientside FF
-------

I was thinking of rewriting the templates in handlebars, rather than razor, calling them using Handlebars.Net. This would 
 - decouple FormFactory from ASP.NET
 - allow js/client side implementations of FormFactory, i.e. FormFactory.Knockout and FormFactory.React (both knockout and react can be made to work against handlebars templates)

**Comment by axygen** [comment]
What's the easiest way to add my own controls?... similar to the DateTime picker. Where would I start? Thank you.

**Comment by mcintyre321** [comment]
Install the Templates project in a playground project to see how the
templates work - they get created in /Views/Shared/Formfactory/

If you only want to use it inside your own project, just add a view there
called MyObject.cshtml, or SomeNamespace.Blah.MyObjet.cshtml

To contribute, you would
- add the view in the Templates project
- use 'Add as link' to add the view to the core FormFactory project, and
set build action to EmbeddedResource
- Add an example of the view to the help pages in the example project

**Comment by patagoniahiker** [comment]
I tried an template (iterative) for a MVC form with the following capabilities (sample) [http://bit.ly/1WbjVGz] Render and submit.

  - [ ]      sortable rows, drag handle (the jquery lib exists)
   2.      Edit Rows: accept data - i.e. editable/items text box, drop down button
   3.      Add Rows: with a plus sign, add a new row to the table.
   4.      Submit the form back MVC action


Even with the basics its giving me an error, when I loop through. I am trying to figure out what I am doing wrong, I would like to work this and contribute, but need some help on basic steps on where to begin at the 
* views, models, DB, and JS

*How should I think about it?*
- [ ] Would I have to think of this *as a new custom control*, where its sortable with a drag handle. Or, would this simply be options to a grid rendering.
- [ ] How can I inject security to the forms, XSS the anti forgery token to auto render as an aspect

Could you please share steps (baby, with snippets), I also plan to add a map down the road :+1:

**Comment by mcintyre321** [comment]
@patagoniahiker 
- For the xss token, I would use a string field with `[Hidden]` attribute
- How to implement the editable table is really up to you. A custom type and FF template is probably the best way to go. IMO the renderers for standard collection types are limited somewhat in scope as they can only be modified by attributes which are tricky to pass dynamic values to. 

If I were implementing your requirement I would probably implement a DataTable type and template, and hook it into my own Mvc.JQuery.Datatables project (which in turn would end up requiring a modfication to enable the sortable/editable plugins). JQuery.DataTables is the most configurable, extensible tables plugin I have found, so would be an awesome addition to FormFactory as it is so flexible. On the other hand it is more complex than needed for your current requirements, so might be more work than you want to do.
